# Generated by Django 4.1 on 2022-08-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_processing', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
